export const mainnetTokens = [
  {
    fullName: 'THORChain',
    name: 'RUNE',
    fullAsset: 'THOR.RUNE',
    chain: 'THOR',
    type: 'NATIVE',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Binance Coin',
    name: 'BNB',
    fullAsset: 'BNB.BNB',
    chain: 'BNB',
    type: 'NATIVE',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Binance Coin',
    name: 'BNB',
    fullAsset: 'THOR.BNB/BNB',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Avalanche',
    name: 'AVAX',
    fullAsset: 'AVAX.AVAX',
    chain: 'AVAX',
    type: 'NATIVE',
    balance: '0',
    decimals: 18,
    price: 0,
  },
  {
    fullName: 'Avalanche',
    name: 'AVAX',
    fullAsset: 'THOR.AVAX/AVAX',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'USD Coin',
    name: 'USDC',
    fullAsset: 'AVAX.USDC-0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E',
    chain: 'AVAX',
    type: 'ERC20',
    balance: '0',
    decimals: 6,
    price: 0,
  },
  {
    fullName: 'Ethereum',
    name: 'ETH',
    fullAsset: 'ETH.ETH',
    chain: 'ETH',
    type: 'NATIVE',
    balance: '0',
    decimals: 18,
    price: 0,
  },
  {
    fullName: 'Ethereum',
    name: 'ETH',
    fullAsset: 'THOR.ETH/ETH',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Bitcoin',
    name: 'BTC',
    fullAsset: 'BTC.BTC',
    chain: 'BTC',
    type: 'NATIVE',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Bitcoin',
    name: 'BTC',
    fullAsset: 'THOR.BTC/BTC',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Binance USD',
    name: 'BUSD',
    fullAsset: 'BNB.BUSD-BD1',
    chain: 'BNB',
    type: 'BEP2',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Binance USD',
    name: 'BUSD',
    fullAsset: 'THOR.BNB/BUSD-BD1',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Bitcoin Cash',
    name: 'BCH',
    fullAsset: 'BCH.BCH',
    chain: 'BCH',
    type: 'NATIVE',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Bitcoin Cash',
    name: 'BCH',
    fullAsset: 'THOR.BCH/BCH',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Litecoin',
    name: 'LTC',
    fullAsset: 'LTC.LTC',
    chain: 'LTC',
    type: 'NATIVE',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Litecoin',
    name: 'LTC',
    fullAsset: 'THOR.LTC/LTC',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Dogecoin',
    name: 'DOGE',
    fullAsset: 'DOGE.DOGE',
    chain: 'DOGE',
    type: 'NATIVE',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Dogecoin',
    name: 'DOGE',
    fullAsset: 'THOR.DOGE/DOGE',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  // {
  //   fullName: 'THORSwap',
  //   name: 'THOR',
  //   fullAsset: 'ETH.THOR-0xa5f2211B9b8170F694421f2046281775E8468044',
  //   chain: 'ETH',
  //   type: 'ERC20',
  //   balance: '0',
  //   decimals: 18,
  //   price: 0,
  // },
  // {
  //   fullName: 'THORSwap',
  //   name: 'THOR',
  //   fullAsset: 'THOR.ETH/THOR-0xa5f2211B9b8170F694421f2046281775E8468044',
  //   chain: 'THOR',
  //   type: 'SYNTH',
  //   balance: '0',
  //   decimals: 8,
  //   price: 0,
  // },
  {
    fullName: 'Aave',
    name: 'AAVE',
    fullAsset: 'ETH.AAVE-0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 18,
    price: 0,
  },
  {
    fullName: 'Aave',
    name: 'AAVE',
    fullAsset: 'THOR.ETH/AAVE-0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Dai',
    name: 'DAI',
    fullAsset: 'ETH.DAI-0x6B175474E89094C44Da98b954EedeAC495271d0F',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 18,
    price: 0,
  },
  {
    fullName: 'Dai',
    name: 'DAI',
    fullAsset: 'THOR.ETH/DAI-0x6B175474E89094C44Da98b954EedeAC495271d0F',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Shapeshift',
    name: 'FOX',
    fullAsset: 'ETH.FOX-0xc770EEfAd204B5180dF6a14Ee197D99d808ee52d',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 18,
    price: 0,
  },
  {
    fullName: 'Shapeshift',
    name: 'FOX',
    fullAsset: 'THOR.ETH/FOX-0xc770EEfAd204B5180dF6a14Ee197D99d808ee52d',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Synthetix',
    name: 'SNX',
    fullAsset: 'ETH.SNX-0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 18,
    price: 0,
  },
  {
    fullName: 'Synthetix',
    name: 'SNX',
    fullAsset: 'THOR.ETH/SNX-0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'THORWallet',
    name: 'TGT',
    fullAsset: 'ETH.TGT-0x108a850856Db3f85d0269a2693D896B394C80325',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 18,
    price: 0,
  },
  {
    fullName: 'THORWallet',
    name: 'TGT',
    fullAsset: 'THOR.ETH/TGT-0x108a850856Db3f85d0269a2693D896B394C80325',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Ultra',
    name: 'UOS',
    fullAsset: 'ETH.UOS-0xD13c7342e1ef687C5ad21b27c2b65D772cAb5C8c',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 4,
    price: 0,
  },
  {
    fullName: 'Ultra',
    name: 'UOS',
    fullAsset: 'THOR.ETH/UOS-0xD13c7342e1ef687C5ad21b27c2b65D772cAb5C8c',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'USD Coin',
    name: 'USDC',
    fullAsset: 'ETH.USDC-0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 6,
    price: 0,
  },
  {
    fullName: 'USD Coin',
    name: 'USDC',
    fullAsset: 'THOR.ETH/USDC-0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Tether USD',
    name: 'USDT',
    fullAsset: 'ETH.USDT-0xdAC17F958D2ee523a2206206994597C13D831ec7',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 6,
    price: 0,
  },
  {
    fullName: 'Tether USD',
    name: 'USDT',
    fullAsset: 'THOR.ETH/USDT-0xdAC17F958D2ee523a2206206994597C13D831ec7',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Wrapped Bitcoin',
    name: 'WBTC',
    fullAsset: 'ETH.WBTC-0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Wrapped Bitcoin',
    name: 'WBTC',
    fullAsset: 'THOR.ETH/WBTC-0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'XDEFI',
    name: 'XDEFI',
    fullAsset: 'ETH.XDEFI-0x72B886d09C117654aB7dA13A14d603001dE0B777',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 18,
    price: 0,
  },
  {
    fullName: 'XDEFI',
    name: 'XDEFI',
    fullAsset: 'THOR.ETH/XDEFI-0x72B886d09C117654aB7dA13A14d603001dE0B777',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'THORStarter',
    name: 'XRUNE',
    fullAsset: 'ETH.XRUNE-0x69fa0feE221AD11012BAb0FdB45d444D3D2Ce71c',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 18,
    price: 0,
  },
  {
    fullName: 'THORStarter',
    name: 'XRUNE',
    fullAsset: 'THOR.ETH/XRUNE-0x69fa0feE221AD11012BAb0FdB45d444D3D2Ce71c',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'yearn.finance',
    name: 'YFI',
    fullAsset: 'ETH.YFI-0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e',
    chain: 'ETH',
    type: 'ERC20',
    balance: '0',
    decimals: 18,
    price: 0,
  },
  {
    fullName: 'yearn.finance',
    name: 'YFI',
    fullAsset: 'THOR.ETH/YFI-0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Travala.com',
    name: 'AVA',
    fullAsset: 'BNB.AVA-645',
    chain: 'BNB',
    type: 'BEP2',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Travala.com',
    name: 'AVA',
    fullAsset: 'THOR.BNB/AVA-645',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Ethereum',
    name: 'ETH',
    fullAsset: 'BNB.ETH-1C9',
    chain: 'BNB',
    type: 'BEP2',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Ethereum',
    name: 'ETH',
    fullAsset: 'THOR.BNB/ETH-1C9',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Bitcoin BEP2',
    name: 'BTCB',
    fullAsset: 'BNB.BTCB-1DE',
    chain: 'BNB',
    type: 'BEP2',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Bitcoin BEP2',
    name: 'BTCB',
    fullAsset: 'THOR.BNB/BTCB-1DE',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Trust Wallet Token',
    name: 'TWT',
    fullAsset: 'BNB.TWT-8C2',
    chain: 'BNB',
    type: 'BEP2',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Trust Wallet Token',
    name: 'TWT',
    fullAsset: 'THOR.BNB/TWT-8C2',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
  {
    fullName: 'Cosmos',
    name: 'ATOM',
    fullAsset: 'GAIA.ATOM',
    chain: 'GAIA',
    type: 'NATIVE',
    balance: '0',
    decimals: 6,
    price: 0,
  },
  {
    fullName: 'Cosmos',
    name: 'ATOM',
    fullAsset: 'THOR.GAIA/ATOM',
    chain: 'THOR',
    type: 'SYNTH',
    balance: '0',
    decimals: 8,
    price: 0,
  },
]
